linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - cyclop
    - goconst
    - gofumpt
    - misspell
    - revive
    - unconvert
    - unparam
    - bodyclose
    - goerr113
    - dupl
    - errchkjson
    - nakedret