version: '3.8'
services:
  cache:
    image: redis/redis-stack:7.2.0-v9
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      - REDIS_ARGS="--requirepass mypassword"
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local