#%RAML 1.0
---
title: RAML Representation of RESTful API
baseUri: http://localhost:8080/api/v1
mediaType: application/json
version: v1.0
/api:
    /v1:
        /health:
            get:
                displayName: GET /api/v1/health
                description: "Handler Function: irkenfunk/SQS/business/handler.IHealthHandler.GetHealthHandler-fm\nComment: "
        /weather:
            /{location}:
                get:
                    displayName: GET /api/v1/weather/{location}
                    description: "Handler Function: irkenfunk/SQS/business/handler.IWeatherHandler.GetWeatherHandler-fm\nComment: "
