// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IHealthHandler is an autogenerated mock type for the IHealthHandler type
type IHealthHandler struct {
	mock.Mock
}

// GetHealthHandler provides a mock function with given fields: rw, r
func (_m *IHealthHandler) GetHealthHandler(rw http.ResponseWriter, r *http.Request) {
	_m.Called(rw, r)
}

// NewIHealthHandler creates a new instance of IHealthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHealthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHealthHandler {
	mock := &IHealthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
