// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	chi "github.com/go-chi/chi/v5"
	mock "github.com/stretchr/testify/mock"
)

// IRouter is an autogenerated mock type for the IRouter type
type IRouter struct {
	mock.Mock
}

// InitRouter provides a mock function with given fields:
func (_m *IRouter) InitRouter() *chi.Mux {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitRouter")
	}

	var r0 *chi.Mux
	if rf, ok := ret.Get(0).(func() *chi.Mux); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chi.Mux)
		}
	}

	return r0
}

// NewIRouter creates a new instance of IRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRouter {
	mock := &IRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
