// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	dtos "codeberg.org/Birkenfunk/SQS/dtos"

	mock "github.com/stretchr/testify/mock"
)

// IWeather is an autogenerated mock type for the IWeather type
type IWeather struct {
	mock.Mock
}

// GetWeather provides a mock function with given fields: location
func (_m *IWeather) GetWeather(location string) *dtos.WeatherDto {
	ret := _m.Called(location)

	if len(ret) == 0 {
		panic("no return value specified for GetWeather")
	}

	var r0 *dtos.WeatherDto
	if rf, ok := ret.Get(0).(func(string) *dtos.WeatherDto); ok {
		r0 = rf(location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.WeatherDto)
		}
	}

	return r0
}

// NewIWeather creates a new instance of IWeather. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWeather(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWeather {
	mock := &IWeather{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
