// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	dtos "codeberg.org/Birkenfunk/SQS/dtos"
	mock "github.com/stretchr/testify/mock"
)

// IWeatherService is an autogenerated mock type for the IWeatherService type
type IWeatherService struct {
	mock.Mock
}

// GetHealth provides a mock function with given fields:
func (_m *IWeatherService) GetHealth() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWeather provides a mock function with given fields: location
func (_m *IWeatherService) GetWeather(location string) (*dtos.WeatherDto, error) {
	ret := _m.Called(location)

	if len(ret) == 0 {
		panic("no return value specified for GetWeather")
	}

	var r0 *dtos.WeatherDto
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*dtos.WeatherDto, error)); ok {
		return rf(location)
	}
	if rf, ok := ret.Get(0).(func(string) *dtos.WeatherDto); ok {
		r0 = rf(location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.WeatherDto)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIWeatherService creates a new instance of IWeatherService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWeatherService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWeatherService {
	mock := &IWeatherService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
