// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IWeatherHandler is an autogenerated mock type for the IWeatherHandler type
type IWeatherHandler struct {
	mock.Mock
}

// GetWeatherHandler provides a mock function with given fields: rw, r
func (_m *IWeatherHandler) GetWeatherHandler(rw http.ResponseWriter, r *http.Request) {
	_m.Called(rw, r)
}

// NewIWeatherHandler creates a new instance of IWeatherHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWeatherHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWeatherHandler {
	mock := &IWeatherHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
