name: Load Test
on:
  push:
    branches:
      - main

jobs:
    load-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Go 1.21
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.x'
        - name: Setup Environment
          run: docker-compose -f ci.docker-compose.yml up -d
        - name: start api
          env:
            PORT: 4000
            REDIS_URL: localhost:1235
            WEATHER_SERVICE_API_URL: http://localhost:1234
          run: go run main.go &
        - name: Load Test
          uses: artilleryio/action-cli@v1
          with:
            command: run artillery.yml