name: Push Actions
on: [ push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build
        run: make linux
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build


  test:
    runs-on: ubuntu-latest
    env:
      WEATHER_SERVICE_API_URL: http://localhost:3000
      PORT: 4000
      REDIS_URL: localhost:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Setup Environment
        run: docker-compose -f integration.docker-compose.yml up -d
      - name: Test
        run: make test_with_coverage
      - name: Tear down
        run: docker-compose -f integration.docker-compose.yml down -v

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: build/

  sonarqube:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Download coverage
          uses: actions/download-artifact@v4
          with:
            name: coverage
            path: build/
        - run: ls -la
        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    needs:
      - test