name: Push Actions
on: [ push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build
        run: make linux


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Setup Environment
        run: docker-compose -f integration.docker-compose.yml up -d
      - name: Test
        run: make test_with_coverage